name: Build Workflow

on:
  push:
    branches:
      - testing


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Other steps for the first workflow
      # ...

      - name: Perform some actions
        run: |
          # Your commands here
          echo "Performing some actions..."

      # Add other steps as needed

