name: Second Workflow

on:
  workflow_run:
    workflows: ["First Workflow"]
    types:
      - completed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Other steps for the second workflow
      # ...
