name: Dep Workflow

on:
  workflow_run:
    workflows: ["Build Workflow"]
    types:
      - completed_success
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Other steps for the second workflow
      # ...
