name: Workflow 2

on:
  push:
    branches:
      - main
  workflow_dispatch:
  

jobs:
  use_run_number:
    runs-on: ubuntu-latest

    steps:
      
    - name: Use GITHUB_RUN_NUMBER from Workflow 1
      run: echo "The run number is $RUN_NUMBER"
